services:
  postgres:
    image: postgres:16-alpine
    container_name: payment_dashboard_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
      POSTGRES_DB: payment_dashboard
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment -d payment_dashboard"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
